name: Build Aarch64

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu libc6-dev-arm64-cross

      - name: Set up environment
        run: |
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      - name: Build for Aarch64
        run: |
          RUSTFLAGS="-C linker=aarch64-linux-gnu-gcc" cargo build --release --target=aarch64-unknown-linux-gnu

      - name: Prepare Artifact Directory
        run: |
          mkdir -p release_package
          cp target/aarch64-unknown-linux-gnu/release/VpnWebServer release_package/
          cp -r resources release_package/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vpn-web-server-build-package
          path: release_package
